In [2]:
import pandas as pd
import numpy as np
# Produkt
p_o = pd.DataFrame([206, 213, 200, 202])
p_w = pd.DataFrame([146, 144, 142, 143])

phi = pd.DataFrame([[1, 206, 206**2], [1, 213, 213**2], [1, 200, 200**2], [1, 202, 200**2]])
print(phi)   
#Pseudoinverse 
phiPlus = np.linalg.pinv(phi)
print(phiPlus)
#Gewichte 
w = np.dot(phiPlus, p_w)
#Vorhersage
p_w_2018 =w[0] + w[1] * 220 + w[2] * 220 * 220
print(format(*p_w_2018))



   0    1      2
0  1  206  42436
1  1  213  45369
2  1  200  40000
3  1  202  40000
[[ 1.63253529e+01 -1.48572471e+01  5.19358468e+01 -5.24039526e+01]
 [-1.52895311e-01  6.93710146e-02 -4.24250042e-01  5.07774338e-01]
 [ 3.64861827e-04  2.07108567e-05  8.43633366e-04 -1.22920605e-03]]
146.01717965565697


In [3]:
from sklearn.linear_model import LinearRegression

#instanziieren
mdl = LinearRegression(fit_intercept = True)
#Modell traning
mdl.fit(p_o, p_w)
#Vorhersage
p_w_2018 = mdl.intercept_ + mdl.coef_ * 220
p_w_2018 = mdl.predict(np.array(220).reshape(-1, 1))

print((np.asscalar(p_w_2018)))

146.02784810126582


C:\Users\Shiyue\AppData\Local\Temp\ipykernel_16016\1287348527.py:11: DeprecationWarning: np.asscalar(a) is deprecated since NumPy v1.16, use a.item() instead
  print((np.asscalar(p_w_2018)))
